# Put main configuration in this file
# See http://seedstack.org/docs/seed/configuration for more information

logging:
  level: INFO

application:
  id: angular-backend
  # Make sure all your application base packages are listed below
  basePackages: [ org.seedstack.samples.angular ]
  databaseFile: /tests/AngularBackend.db
  imageFolder: /tests/AngularBackEnd-images/

rest:
  path: /api

web:
  cors:
    #path: /api
    enabled: true
    properties:
      supportedMethods: GET, POST, HEAD, OPTIONS, PUT, DELETE

jdbc:
  datasources:
    appDatasource:
      url: jdbc:hsqldb:file:${application.databaseFile}

jpa:
  units:
    appUnit:
      datasource: appDatasource
      properties:
        hibernate.dialect: org.hibernate.dialect.HSQLDialect
        hibernate.hbm2ddl.auto: update